ian:
 apid: IAN-LX-XXX-02
 ap-id: IANLXXXX02
 project-name: mail-notify
 
springdoc:
  swagger-ui:
   path: /swagger-ui-custom.html
 
spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump,loggers
  metrics:
    export:
      prometheus:
        enabled: true